import 'dart:async';
import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:shared_preferences/shared_preferences.dart';
import '../models/models.dart';
import '../firebase_options.dart';
import 'mock_data.dart';

class FirebaseService {
  static bool isFirebaseInitialized = false;
  static bool useDemoMode = true; // Automatically falls back to Demo Mode if Firebase init fails

  // Active Session
  static UserModel? currentUser;
  static List<UserModel> _firestoreUsers = [];
  static StreamSubscription? _usersSubscription;

  static void startUsersSynchronizer() {
    if (useDemoMode) return;
    _usersSubscription?.cancel();
    _usersSubscription = FirebaseFirestore.instance.collection('users').snapshots().listen((snapshot) {
      _firestoreUsers = snapshot.docs.map((doc) {
        Map<String, dynamic> data = doc.data();
        data['uid'] = doc.id;
        return UserModel.fromMap(data);
      }).toList();
    }, onError: (err) {
      debugPrint("Kullanıcı senkronizasyon hatası (Giriş yapılınca düzelecektir): $err");
    });
  }

  static Future<void> saveSession(String uid, String role) async {
    try {
      final prefs = await SharedPreferences.getInstance();
      await prefs.setString('session_uid', uid);
      await prefs.setString('session_role', role);
    } catch (_) {}
  }

  static Future<void> clearSession() async {
    try {
      final prefs = await SharedPreferences.getInstance();
      await prefs.remove('session_uid');
      await prefs.remove('session_role');
    } catch (_) {}
  }

  static Future<UserModel?> tryAutoLogin() async {
    try {
      final prefs = await SharedPreferences.getInstance();
      final uid = prefs.getString('session_uid');
      if (uid != null && uid.isNotEmpty) {
        final user = await getUserById(uid);
        if (user != null) {
          currentUser = user;
          startUsersSynchronizer();
          return user;
        }
      }
    } catch (_) {}
    return null;
  }

  // Mock Databases (In-Memory for Demo Mode)
  static final List<UserModel> _mockUsers = MockData.getInitialUsers();
  static final Map<String, List<DeliveryAddress>> _mockAddresses = MockData.getInitialAddresses();
  static final Map<String, List<RestaurantBranch>> _mockBranches = MockData.getInitialBranches();
  static final List<FoodItem> _mockFoodItems = MockData.getInitialFoodItems();
  static final List<OrderModel> _mockOrders = MockData.getInitialOrders();

  // Stream Controllers for Mock Real-Time Updates
  static final StreamController<List<FoodItem>> _foodStreamController = StreamController<List<FoodItem>>.broadcast();
  static final StreamController<List<OrderModel>> _orderStreamController = StreamController<List<OrderModel>>.broadcast();
  static final StreamController<List<UserModel>> _usersStreamController = StreamController<List<UserModel>>.broadcast();
  static final StreamController<List<DeliveryAddress>> _addressStreamController = StreamController<List<DeliveryAddress>>.broadcast();
  static final StreamController<List<RestaurantBranch>> _branchStreamController = StreamController<List<RestaurantBranch>>.broadcast();
  static final List<BranchInvitation> _mockBranchInvitations = [];
  static final StreamController<List<BranchInvitation>> _invitationsStreamController = StreamController<List<BranchInvitation>>.broadcast();

  // Initialization
  static Future<void> initialize() async {
    try {
      // Firebase options is typically generated by FlutterFire CLI.
      // We attempt initialization. If no configuration is present, it will throw an error.
      await Firebase.initializeApp(
        options: DefaultFirebaseOptions.currentPlatform,
      );
      isFirebaseInitialized = true;
      useDemoMode = false;
      debugPrint("Firebase successfully initialized! App will run on Cloud Firestore.");
      
      // Real-time Firestore users collection synchronizer will start only after auth to avoid PERMISSION_DENIED.
    } catch (e) {
      isFirebaseInitialized = false;
      useDemoMode = true;
      debugPrint("Firebase initialization failed ($e). App will run in Offline Demo Mode.");
    }

    // Initialize mock streams
    _foodStreamController.add(_mockFoodItems);
    _orderStreamController.add(_mockOrders);
    _usersStreamController.add(_mockUsers);
  }

  // Auth Operations
  static Future<String?> signIn({
    required String email,
    required String password,
  }) async {
    if (!useDemoMode) {
      try {
        UserCredential credential = await FirebaseAuth.instance.signInWithEmailAndPassword(
          email: email,
          password: password,
        );

        // Fetch User details from Firestore
        DocumentSnapshot userDoc = await FirebaseFirestore.instance.collection('users').doc(credential.user!.uid).get();

        if (userDoc.exists) {
          Map<String, dynamic> data = userDoc.data() as Map<String, dynamic>;
          currentUser = UserModel.fromMap(data);
          startUsersSynchronizer();
          await saveSession(currentUser!.uid, currentUser!.role);
          return null; // Success
        } else {
          await FirebaseAuth.instance.signOut();
          return "Kullanıcı kaydı bulunamadı.";
        }
      } on FirebaseAuthException catch (e) {
        if (e.code == 'user-not-found') return "Bu e-posta adresiyle kayıtlı kullanıcı bulunamadı.";
        if (e.code == 'wrong-password') return "Hatalı şifre girdiniz.";
        return e.message ?? "Giriş yapılamadı.";
      } catch (e) {
        return "Bir hata oluştu: ${e.toString()}";
      }
    } else {
      // Demo Mode Authentication
      await Future.delayed(const Duration(milliseconds: 800)); // Simulate network latency

      // Check if user exists in mock database
      final match = _mockUsers.firstWhere(
        (u) => u.email.toLowerCase() == email.toLowerCase(),
        orElse: () => UserModel(uid: '', fullName: '', email: '', role: '', createdAt: DateTime.now()),
      );

      if (match.uid.isEmpty) {
        if (email.toLowerCase() == 'musteri@yemek.com') {
          currentUser = _mockUsers.firstWhere((u) => u.uid == 'demo_customer_1');
          await saveSession(currentUser!.uid, currentUser!.role);
          return null;
        }
        if (email.toLowerCase() == 'restoran@yemek.com') {
          currentUser = _mockUsers.firstWhere((u) => u.uid == 'demo_restaurant_1');
          await saveSession(currentUser!.uid, currentUser!.role);
          return null;
        }
        if (email.toLowerCase() == 'destek@yemek.com') {
          currentUser = _mockUsers.firstWhere((u) => u.uid == 'demo_support_1');
          await saveSession(currentUser!.uid, currentUser!.role);
          return null;
        }
        return "Geçersiz e-posta adresi veya şifre.";
      }

      currentUser = match;
      await saveSession(currentUser!.uid, currentUser!.role);
      return null; // Success
    }
  }

  static Future<String?> signUp({
    required String email,
    required String password,
    required String fullName,
    required String role,
    String phone = '',
    String address = '',
    String restaurantName = '',
    String restaurantAddress = '',
  }) async {
    if (!useDemoMode) {
      try {
        UserCredential credential = await FirebaseAuth.instance.createUserWithEmailAndPassword(
          email: email,
          password: password,
        );

        // Query Firestore users collection to check if empty
        final usersSnapshot = await FirebaseFirestore.instance.collection('users').limit(1).get();
        final bool isFirstUser = usersSnapshot.docs.isEmpty;
        
        final finalRole = isFirstUser ? 'admin' : role;
        final finalStatus = finalRole == 'restaurant_owner' ? 'pending_approval' : 'active';

        UserModel newUser = UserModel(
          uid: credential.user!.uid,
          fullName: fullName,
          email: email,
          role: finalRole,
          status: finalStatus,
          createdAt: DateTime.now(),
          phone: phone,
          address: address,
          restaurantName: restaurantName,
          restaurantAddress: restaurantAddress,
        );

        // Save to Firestore users collection
        await FirebaseFirestore.instance.collection('users').doc(newUser.uid).set(newUser.toMap());
        
        currentUser = newUser;
        startUsersSynchronizer();
        await saveSession(currentUser!.uid, currentUser!.role);
        return null; // Success
      } on FirebaseAuthException catch (e) {
        if (e.code == 'email-already-in-use') return "Bu e-posta adresi zaten kullanımda.";
        if (e.code == 'weak-password') return "Belirlenen şifre çok zayıf.";
        return e.message ?? "Kayıt işlemi başarısız.";
      } catch (e) {
        return "Bir hata oluştu: ${e.toString()}";
      }
    } else {
      // Demo Mode Registration
      await Future.delayed(const Duration(milliseconds: 800));

      final exists = _mockUsers.any((u) => u.email.toLowerCase() == email.toLowerCase());
      if (exists) {
        return "Bu e-posta adresi zaten kullanımda.";
      }

      // Check if there are no manually registered demo users yet
      final bool isFirstManualRegister = !_mockUsers.any((u) => u.uid != 'demo_customer_1' && u.uid != 'demo_restaurant_1');
      final finalRole = isFirstManualRegister ? 'admin' : role;
      final finalStatus = finalRole == 'restaurant_owner' ? 'pending_approval' : 'active';

      UserModel newUser = UserModel(
        uid: 'demo_user_${DateTime.now().millisecondsSinceEpoch}',
        fullName: fullName,
        email: email,
        role: finalRole,
        status: finalStatus,
        createdAt: DateTime.now(),
        phone: phone,
        address: address,
        restaurantName: restaurantName,
        restaurantAddress: restaurantAddress,
      );

      _mockUsers.add(newUser);
      _usersStreamController.add(List.from(_mockUsers));
      currentUser = newUser;
      await saveSession(currentUser!.uid, currentUser!.role);
      return null; // Success
    }
  }

  static Future<String?> resetPassword(String email) async {
    if (!useDemoMode) {
      try {
        await FirebaseAuth.instance.sendPasswordResetEmail(email: email);
        return null; // Success
      } on FirebaseAuthException catch (e) {
        return e.message ?? "Şifre sıfırlama e-postası gönderilemedi.";
      } catch (e) {
        return e.toString();
      }
    } else {
      await Future.delayed(const Duration(milliseconds: 600));
      return null; // Mock Success
    }
  }

  static Future<void> signOut() async {
    _usersSubscription?.cancel();
    _usersSubscription = null;
    _firestoreUsers = [];
    if (!useDemoMode) {
      await FirebaseAuth.instance.signOut();
    }
    await clearSession();
    currentUser = null;
  }

  // Database Streams (Real-Time)
  static Stream<List<FoodItem>> streamFoodItems() async* {
    if (!useDemoMode) {
      yield* FirebaseFirestore.instance.collection('meals').snapshots().map((snapshot) {
        return snapshot.docs.map((doc) {
          Map<String, dynamic> data = doc.data();
          data['id'] = doc.id;
          return FoodItem.fromMap(data);
        }).toList();
      });
    } else {
      yield List.from(_mockFoodItems);
      yield* _foodStreamController.stream.map((_) => List.from(_mockFoodItems));
    }
  }

  static Stream<List<OrderModel>> streamOrders() async* {
    if (!useDemoMode) {
      yield* FirebaseFirestore.instance.collection('orders').orderBy('createdAt', descending: true).snapshots().map((snapshot) {
        return snapshot.docs.map((doc) {
          Map<String, dynamic> data = doc.data();
          data['id'] = doc.id;
          return OrderModel.fromMap(data);
        }).toList();
      });
    } else {
      yield List.from(_mockOrders);
      yield* _orderStreamController.stream.map((_) => List.from(_mockOrders));
    }
  }

  // Add Meal (Restaurant Owner)
  static Future<String?> addFoodItem(FoodItem meal) async {
    if (!useDemoMode) {
      try {
        await FirebaseFirestore.instance.collection('meals').add(meal.toMap());
        return null;
      } catch (e) {
        return e.toString();
      }
    } else {
      await Future.delayed(const Duration(milliseconds: 500));
      FoodItem newItem = FoodItem(
        id: 'food_${DateTime.now().millisecondsSinceEpoch}',
        name: meal.name,
        description: meal.description,
        price: meal.price,
        imageUrl: meal.imageUrl.isNotEmpty ? meal.imageUrl : 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3',
        category: meal.category,
        rating: meal.rating,
        stock: meal.stock,
        restaurantOwnerId: meal.restaurantOwnerId.isNotEmpty ? meal.restaurantOwnerId : (currentUser?.uid ?? ''),
      );
      _mockFoodItems.insert(0, newItem);
      _foodStreamController.add(List.from(_mockFoodItems));
      return null;
    }
  }

  // Delete Meal (Restaurant Owner)
  static Future<String?> deleteFoodItem(String foodId) async {
    if (!useDemoMode) {
      try {
        await FirebaseFirestore.instance.collection('meals').doc(foodId).delete();
        return null;
      } catch (e) {
        return e.toString();
      }
    } else {
      await Future.delayed(const Duration(milliseconds: 400));
      _mockFoodItems.removeWhere((item) => item.id == foodId);
      _foodStreamController.add(List.from(_mockFoodItems));
      return null;
    }
  }

  // Edit Meal (Restaurant Owner)
  static Future<String?> updateFoodItem(FoodItem item) async {
    if (!useDemoMode) {
      try {
        await FirebaseFirestore.instance.collection('meals').doc(item.id).update(item.toMap());
        return null;
      } catch (e) {
        return e.toString();
      }
    } else {
      final idx = _mockFoodItems.indexWhere((f) => f.id == item.id);
      if (idx != -1) {
        _mockFoodItems[idx] = item;
        _foodStreamController.add(List.from(_mockFoodItems));
      }
      return null;
    }
  }

  // Submit Order (Customer)
  static Future<String?> placeOrder(List<OrderItem> items, double total, {bool isTakeaway = false, String? note}) async {
    if (currentUser == null) return "Giriş yapmış bir kullanıcı bulunamadı.";

    if (!useDemoMode) {
      try {
        OrderModel newOrder = OrderModel(
          id: '',
          customerId: currentUser!.uid,
          customerName: currentUser!.fullName,
          items: items,
          totalAmount: total,
          status: 'pending',
          createdAt: DateTime.now(),
          isTakeaway: isTakeaway,
          note: note,
        );

        await FirebaseFirestore.instance.collection('orders').add(newOrder.toMap());
        return null;
      } catch (e) {
        return e.toString();
      }
    } else {
      await Future.delayed(const Duration(milliseconds: 600));
      OrderModel newOrder = OrderModel(
        id: 'ord_${DateTime.now().millisecondsSinceEpoch}',
        customerId: currentUser!.uid,
        customerName: currentUser!.fullName,
        items: items,
        totalAmount: total,
        status: 'pending',
        createdAt: DateTime.now(),
        isTakeaway: isTakeaway,
        note: note,
      );

      _mockOrders.insert(0, newOrder);
      _orderStreamController.add(List.from(_mockOrders));
      return null;
    }
  }

  // Update Order Status (Restaurant Owner / Admin)
  static Future<String?> updateOrderStatus(String orderId, String newStatus) async {
    if (!useDemoMode) {
      try {
        await FirebaseFirestore.instance.collection('orders').doc(orderId).update({
          'status': newStatus,
        });
        return null;
      } catch (e) {
        return e.toString();
      }
    } else {
      await Future.delayed(const Duration(milliseconds: 300));
      int index = _mockOrders.indexWhere((o) => o.id == orderId);
      if (index != -1) {
        _mockOrders[index].status = newStatus;
        _orderStreamController.add(List.from(_mockOrders));
        return null;
      }
      return "Sipariş bulunamadı.";
    }
  }

  // Update Order Rating given by Customer
  static Future<String?> updateOrderRating(String orderId, int rating) async {
    if (!useDemoMode) {
      try {
        await FirebaseFirestore.instance.collection('orders').doc(orderId).update({
          'rating': rating,
        });
        return null;
      } catch (e) {
        return e.toString();
      }
    } else {
      await Future.delayed(const Duration(milliseconds: 200));
      int index = _mockOrders.indexWhere((o) => o.id == orderId);
      if (index != -1) {
        _mockOrders[index].rating = rating;
        _orderStreamController.add(List.from(_mockOrders));
        return null;
      }
      return "Sipariş bulunamadı.";
    }
  }

  // Get a single User by ID (Production and Demo compliant)
  static Future<UserModel?> getUserById(String uid) async {
    if (!useDemoMode) {
      try {
        final doc = await FirebaseFirestore.instance.collection('users').doc(uid).get();
        if (doc.exists && doc.data() != null) {
          final data = doc.data()!;
          data['uid'] = doc.id;
          return UserModel.fromMap(data);
        }
        return null;
      } catch (_) {
        return null;
      }
    } else {
      final idx = _mockUsers.indexWhere((u) => u.uid == uid);
      if (idx != -1) {
        return _mockUsers[idx];
      }
      return null;
    }
  }

  // Stream of all Users in the system (Admin only)
  static Stream<List<UserModel>> streamUsers() {
    if (!useDemoMode) {
      return FirebaseFirestore.instance
          .collection('users')
          .orderBy('createdAt', descending: true)
          .snapshots()
          .map((snapshot) {
        return snapshot.docs.map((doc) {
          Map<String, dynamic> data = doc.data();
          data['uid'] = doc.id;
          return UserModel.fromMap(data);
        }).toList();
      });
    } else {
      return _usersStreamController.stream;
    }
  }

  // Update user role (Admin authorization)
  static Future<String?> updateUserRole(String uid, String newRole) async {
    if (!useDemoMode) {
      try {
        await FirebaseFirestore.instance.collection('users').doc(uid).update({
          'role': newRole,
        });
        return null;
      } catch (e) {
        return e.toString();
      }
    } else {
      await Future.delayed(const Duration(milliseconds: 300));
      int index = _mockUsers.indexWhere((u) => u.uid == uid);
      if (index != -1) {
        _mockUsers[index] = UserModel(
          uid: _mockUsers[index].uid,
          fullName: _mockUsers[index].fullName,
          email: _mockUsers[index].email,
          role: newRole,
          status: _mockUsers[index].status,
          createdAt: _mockUsers[index].createdAt,
        );
        _usersStreamController.add(List.from(_mockUsers));
        
        // If current user's role is updated, sync it live as well
        if (currentUser?.uid == uid) {
          currentUser = _mockUsers[index];
        }
        return null;
      }
      return "Kullanıcı bulunamadı.";
    }
  }

  // ─────────────────────────────────────────
  // PROFILE UPDATE
  // ─────────────────────────────────────────
  static Future<String?> updateUserProfile({
    required String uid,
    String? fullName,
    String? email,
    String? phone,
    String? address,
    String? selectedAddressId,
    String? restaurantName,
    String? restaurantAddress,
    double? minOrderAmount,
    String? restaurantLogo,
    String? restaurantDescription,
    double? maxDeliveryDistance,
    String? role,
    String? status,
  }) async {
    if (!useDemoMode) {
      try {
        final data = <String, dynamic>{};
        if (fullName != null) data['fullName'] = fullName;
        if (email != null) data['email'] = email;
        if (phone != null) data['phone'] = phone;
        if (address != null) data['address'] = address;
        if (selectedAddressId != null) data['selectedAddressId'] = selectedAddressId;
        if (restaurantName != null) data['restaurantName'] = restaurantName;
        if (restaurantAddress != null) data['restaurantAddress'] = restaurantAddress;
        if (minOrderAmount != null) data['minOrderAmount'] = minOrderAmount;
        if (restaurantLogo != null) data['restaurantLogo'] = restaurantLogo;
        if (restaurantDescription != null) data['restaurantDescription'] = restaurantDescription;
        if (maxDeliveryDistance != null) data['maxDeliveryDistance'] = maxDeliveryDistance;
        if (role != null) data['role'] = role;
        if (status != null) data['status'] = status;
        
        await FirebaseFirestore.instance.collection('users').doc(uid).update(data);
        if (currentUser?.uid == uid) {
          currentUser = currentUser!.copyWith(
            fullName: fullName,
            email: email,
            phone: phone,
            address: address,
            selectedAddressId: selectedAddressId,
            restaurantName: restaurantName,
            restaurantAddress: restaurantAddress,
            minOrderAmount: minOrderAmount,
            restaurantLogo: restaurantLogo,
            restaurantDescription: restaurantDescription,
            maxDeliveryDistance: maxDeliveryDistance,
            role: role,
            status: status,
          );
        }
        return null;
      } catch (e) {
        return e.toString();
      }
    } else {
      await Future.delayed(const Duration(milliseconds: 300));
      final idx = _mockUsers.indexWhere((u) => u.uid == uid);
      if (idx != -1) {
        _mockUsers[idx] = _mockUsers[idx].copyWith(
          fullName: fullName,
          email: email,
          phone: phone,
          address: address,
          selectedAddressId: selectedAddressId,
          restaurantName: restaurantName,
          restaurantAddress: restaurantAddress,
          minOrderAmount: minOrderAmount,
          restaurantLogo: restaurantLogo,
          restaurantDescription: restaurantDescription,
          maxDeliveryDistance: maxDeliveryDistance,
          role: role,
          status: status,
        );
        if (currentUser?.uid == uid) currentUser = _mockUsers[idx];
        _usersStreamController.add(List.from(_mockUsers));
      }
      return null;
    }
  }

  // Deletes a restaurant user and cascaded food items
  static Future<String?> deleteRestaurant(String uid) async {
    if (!useDemoMode) {
      try {
        await FirebaseFirestore.instance.collection('users').doc(uid).delete();
        final mealsSnapshot = await FirebaseFirestore.instance
            .collection('meals')
            .where('restaurantOwnerId', isEqualTo: uid)
            .get();
        for (var doc in mealsSnapshot.docs) {
          await doc.reference.delete();
        }
        return null;
      } catch (e) {
        return e.toString();
      }
    } else {
      await Future.delayed(const Duration(milliseconds: 300));
      _mockUsers.removeWhere((u) => u.uid == uid);
      _mockFoodItems.removeWhere((f) => f.restaurantOwnerId == uid);
      _usersStreamController.add(List.from(_mockUsers));
      _foodStreamController.add(List.from(_mockFoodItems));
      return null;
    }
  }

  static Future<String?> selectAddress(String uid, String addressId, String addressText, String addressPhone) async {
    return updateUserProfile(
      uid: uid,
      address: addressText,
      phone: addressPhone,
      selectedAddressId: addressId,
    );
  }

  // ─────────────────────────────────────────
  // DELIVERY ADDRESSES (Customer)
  // ─────────────────────────────────────────


  static Stream<List<DeliveryAddress>> streamAddresses(String uid) async* {
    if (!useDemoMode) {
      yield* FirebaseFirestore.instance
          .collection('users').doc(uid).collection('addresses')
          .snapshots()
          .map((s) => s.docs.map((d) => DeliveryAddress.fromMap(d.data())).toList());
    } else {
      yield List.from(_mockAddresses[uid] ?? []);
      yield* _addressStreamController.stream.map((_) => List.from(_mockAddresses[uid] ?? []));
    }
  }

  static Future<String?> saveAddress(String uid, DeliveryAddress addr) async {
    if (!useDemoMode) {
      try {
        await FirebaseFirestore.instance
            .collection('users').doc(uid).collection('addresses')
            .doc(addr.id).set(addr.toMap());
        return null;
      } catch (e) {
        return e.toString();
      }
    } else {
      await Future.delayed(const Duration(milliseconds: 200));
      _mockAddresses.putIfAbsent(uid, () => []);
      final list = _mockAddresses[uid]!;
      final idx = list.indexWhere((a) => a.id == addr.id);
      if (idx == -1) { list.add(addr); } else { list[idx] = addr; }
      _addressStreamController.add(List.from(list));
      return null;
    }
  }

  static Future<String?> deleteAddress(String uid, String addressId) async {
    if (!useDemoMode) {
      try {
        await FirebaseFirestore.instance
            .collection('users').doc(uid).collection('addresses')
            .doc(addressId).delete();
        return null;
      } catch (e) {
        return e.toString();
      }
    } else {
      _mockAddresses[uid]?.removeWhere((a) => a.id == addressId);
      _addressStreamController.add(List.from(_mockAddresses[uid] ?? []));
      return null;
    }
  }

  // ─────────────────────────────────────────
  // RESTAURANT BRANCHES
  // ─────────────────────────────────────────


  static Stream<List<RestaurantBranch>> streamBranches(String uid) async* {
    if (!useDemoMode) {
      yield* FirebaseFirestore.instance
          .collection('restaurants').doc(uid).collection('branches')
          .snapshots()
          .map((s) => s.docs.map((d) => RestaurantBranch.fromMap(d.data())).toList());
    } else {
      yield List.from(_mockBranches[uid] ?? []);
      yield* _branchStreamController.stream.map((_) => List.from(_mockBranches[uid] ?? []));
    }
  }

  static Future<String?> saveBranch(String uid, RestaurantBranch branch) async {
    if (!useDemoMode) {
      try {
        await FirebaseFirestore.instance
            .collection('restaurants').doc(uid).collection('branches')
            .doc(branch.id).set(branch.toMap());
        return null;
      } catch (e) {
        return e.toString();
      }
    } else {
      await Future.delayed(const Duration(milliseconds: 200));
      _mockBranches.putIfAbsent(uid, () => []);
      final list = _mockBranches[uid]!;
      final idx = list.indexWhere((b) => b.id == branch.id);
      if (idx == -1) { list.add(branch); } else { list[idx] = branch; }
      _branchStreamController.add(List.from(list));
      return null;
    }
  }

  static Future<String?> deleteBranch(String uid, String branchId) async {
    if (!useDemoMode) {
      try {
        await FirebaseFirestore.instance
            .collection('restaurants').doc(uid).collection('branches')
            .doc(branchId).delete();
        return null;
      } catch (e) {
        return e.toString();
      }
    } else {
      _mockBranches[uid]?.removeWhere((b) => b.id == branchId);
      _branchStreamController.add(List.from(_mockBranches[uid] ?? []));
      return null;
    }
  }

  // ─────────────────────────────────────────
  // FOOD ITEM CRUD (edit + delete)
  // ─────────────────────────────────────────
  // DISCOUNT CODES
  // ─────────────────────────────────────────
  static final StreamController<List<DiscountCode>> _discountStreamController =
      StreamController<List<DiscountCode>>.broadcast();

  static final List<DiscountCode> _mockDiscountCodes = MockData.getInitialDiscountCodes();

  static Stream<List<DiscountCode>> streamDiscountCodes(String ownerUid) async* {
    if (!useDemoMode) {
      yield* FirebaseFirestore.instance
          .collection('discount_codes')
          .where('restaurantOwnerId', isEqualTo: ownerUid)
          .snapshots()
          .map((s) => s.docs.map((d) => DiscountCode.fromMap(d.data())).toList());
    } else {
      yield _mockDiscountCodes.where((d) => d.restaurantOwnerId == ownerUid).toList();
      yield* _discountStreamController.stream.map((_) =>
          _mockDiscountCodes.where((d) => d.restaurantOwnerId == ownerUid).toList());
    }
  }

  static Future<String?> saveDiscountCode(DiscountCode code) async {
    final hasEmptyId = code.id.isEmpty;
    String finalId = code.id;
    if (hasEmptyId) {
      finalId = !useDemoMode 
          ? FirebaseFirestore.instance.collection('discount_codes').doc().id 
          : "disc_${DateTime.now().millisecondsSinceEpoch}";
    }
    final finalCode = code.copyWith(id: finalId);

    if (!useDemoMode) {
      try {
        await FirebaseFirestore.instance
            .collection('discount_codes').doc(finalCode.id).set(finalCode.toMap());
        return null;
      } catch (e) {
        return e.toString();
      }
    } else {
      final idx = _mockDiscountCodes.indexWhere((d) => d.id == finalCode.id);
      if (idx == -1) { _mockDiscountCodes.add(finalCode); } else { _mockDiscountCodes[idx] = finalCode; }
      _discountStreamController.add(List.from(_mockDiscountCodes));
      return null;
    }
  }

  static Future<String?> deleteDiscountCode(String id) async {
    if (!useDemoMode) {
      try {
        await FirebaseFirestore.instance.collection('discount_codes').doc(id).delete();
        return null;
      } catch (e) {
        return e.toString();
      }
    } else {
      _mockDiscountCodes.removeWhere((d) => d.id == id);
      _discountStreamController.add(List.from(_mockDiscountCodes));
      return null;
    }
  }

  /// Validate a discount code and return DiscountCode if valid, null otherwise
  static Future<DiscountCode?> validateDiscountCode(String code, double cartTotal) async {
    if (!useDemoMode) {
      try {
        final snap = await FirebaseFirestore.instance
            .collection('discount_codes')
            .where('code', isEqualTo: code.toUpperCase())
            .limit(1)
            .get();
        if (snap.docs.isEmpty) return null;
        final dc = DiscountCode.fromMap(snap.docs.first.data());
        if (!dc.isValid || cartTotal < dc.minimumOrderAmount) return null;
        return dc;
      } catch (_) {
        return null;
      }
    } else {
      await Future.delayed(const Duration(milliseconds: 400));
      try {
        return _mockDiscountCodes.firstWhere(
          (d) => d.code == code.toUpperCase() && d.isValid && cartTotal >= d.minimumOrderAmount,
        );
      } catch (_) {
        return null;
      }
    }
  }

  // Deterministic, realistic distance generator between two text addresses
  static String calculateDistanceString(String addr1, String addr2) {
    if (addr1.isEmpty || addr2.isEmpty) return "350 m";

    // Simple deterministic hash of both addresses combined
    int hash = 0;
    final combined = "${addr1.toLowerCase().trim()}_${addr2.toLowerCase().trim()}";
    for (int i = 0; i < combined.length; i++) {
      hash = combined.codeUnitAt(i) + ((hash << 5) - hash);
    }

    // Normalize to a realistic delivery distance between 150 and 2400 meters
    final int meters = 150 + (hash.abs() % 2251);

    if (meters >= 1000) {
      final double km = meters / 1000.0;
      return "${km.toStringAsFixed(1)} km";
    } else {
      return "$meters m";
    }
  }

  // ─────────────────────────────────────────
  // NEARBY RESTAURANTS (text-based matching)
  // ─────────────────────────────────────────
  static List<UserModel> getNearbyRestaurants(String userAddress) {
    if (userAddress.trim().isEmpty) return [];
    // Extract keywords (split by comma/space, filter short words)
    final keywords = userAddress
        .toLowerCase()
        .split(RegExp(r'[,\s]+'))
        .where((w) => w.length >= 3)
        .toList();

    final sourceList = useDemoMode ? _mockUsers : _firestoreUsers;
    final restaurants = sourceList.where((u) => u.role == 'restaurant_owner' && u.status == 'active').toList();
    return restaurants.where((r) {
      final haystack = '${r.restaurantAddress} ${r.restaurantName}'.toLowerCase();
      return keywords.any((kw) => haystack.contains(kw));
    }).toList();
  }

  static bool isRestaurantOwnerActiveSync(String ownerId) {
    final list = useDemoMode ? _mockUsers : _firestoreUsers;
    final user = list.firstWhere(
      (u) => u.uid == ownerId,
      orElse: () => UserModel(uid: '', fullName: '', email: '', role: '', createdAt: DateTime.now()),
    );
    if (user.uid.isEmpty) return true; // Fallback to true if owner is not loaded yet (e.g. offline defaults)
    if (user.role == 'restaurant_owner') {
      return user.status == 'active';
    }
    return true;
  }

  // ─────────────────────────────────────────
  // DYNAMIC CATEGORIES MANAGEMENT
  // ─────────────────────────────────────────
  static final StreamController<List<String>> _categoryStreamController =
      StreamController<List<String>>.broadcast();
  static final List<String> _mockCategories = ["Çorba", "Ana Yemek", "Tatlı", "İçecek"];

  static Stream<List<String>> streamCategories() async* {
    if (!useDemoMode) {
      yield* FirebaseFirestore.instance
          .collection('categories')
          .snapshots()
          .map((s) => s.docs.map((d) => d.id).toList());
    } else {
      yield List.from(_mockCategories);
      yield* _categoryStreamController.stream.map((_) => List.from(_mockCategories));
    }
  }

  static Future<String?> addCategory(String categoryName) async {
    final name = categoryName.trim();
    if (name.isEmpty) return "Kategori adı boş olamaz";
    if (!useDemoMode) {
      try {
        await FirebaseFirestore.instance.collection('categories').doc(name).set({});
        return null;
      } catch (e) {
        return e.toString();
      }
    } else {
      if (!_mockCategories.contains(name)) {
        _mockCategories.add(name);
        _categoryStreamController.add(List.from(_mockCategories));
      }
      return null;
    }
  }

  static Future<String?> deleteCategory(String categoryName) async {
    if (!useDemoMode) {
      try {
        await FirebaseFirestore.instance.collection('categories').doc(categoryName).delete();
        return null;
      } catch (e) {
        return e.toString();
      }
    } else {
      _mockCategories.remove(categoryName);
      _categoryStreamController.add(List.from(_mockCategories));
      return null;
    }
  }

  // ─────────────────────────────────────────
  // LIVE SUPPORT CHAT
  // ─────────────────────────────────────────
  static final StreamController<List<ChatSession>> _chatSessionsController =
      StreamController<List<ChatSession>>.broadcast();
  static final Map<String, StreamController<ChatSession>> _chatRoomControllers = {};

  static final List<ChatSession> _mockChatSessions = MockData.getInitialChatSessions();

  /// Customer: open a new support session (or return existing open one) associated with a specific order
  static Future<ChatSession?> startChatSession([String? orderId]) async {
    final user = currentUser;
    if (user == null) return null;

    if (!useDemoMode) {
      try {
        // Check if customer already has a non-closed session for this order
        var query = FirebaseFirestore.instance
            .collection('support_chats')
            .where('customerId', isEqualTo: user.uid)
            .where('status', whereIn: ['waiting', 'active']);
        if (orderId != null) {
          query = query.where('orderId', isEqualTo: orderId);
        }
        final existing = await query.limit(1).get();
        if (existing.docs.isNotEmpty) {
          return ChatSession.fromMap(existing.docs.first.data());
        }
        final id = 'chat_${DateTime.now().millisecondsSinceEpoch}';
        final session = ChatSession(
          id: id,
          customerId: user.uid,
          customerName: user.fullName,
          status: 'waiting',
          createdAt: DateTime.now(),
          updatedAt: DateTime.now(),
          orderId: orderId,
        );
        await FirebaseFirestore.instance
            .collection('support_chats').doc(id).set(session.toMap());
        return session;
      } catch (_) {
        return null;
      }
    } else {
      await Future.delayed(const Duration(milliseconds: 600));
      // Return existing open session if any for this order
      final existing = _mockChatSessions.firstWhere(
        (s) => s.customerId == user.uid && 
               (orderId == null || s.orderId == orderId) && 
               (s.isWaiting || s.isActive),
        orElse: () => ChatSession(id: '', customerId: '', customerName: '', createdAt: DateTime.now(), updatedAt: DateTime.now()),
      );
      if (existing.id.isNotEmpty) return existing;

      final session = ChatSession(
        id: 'chat_${DateTime.now().millisecondsSinceEpoch}',
        customerId: user.uid,
        customerName: user.fullName,
        status: 'waiting',
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
        orderId: orderId,
      );
      _mockChatSessions.add(session);
      _chatSessionsController.add(List.from(_mockChatSessions));
      return session;
    }
  }

  /// Rate a resolved or closed support session
  static Future<String?> rateSupportSession(String sessionId, int rating) async {
    if (!useDemoMode) {
      try {
        await FirebaseFirestore.instance.collection('support_chats').doc(sessionId).update({
          'rating': rating,
        });
        return null;
      } catch (e) {
        return e.toString();
      }
    } else {
      await Future.delayed(const Duration(milliseconds: 200));
      int index = _mockChatSessions.indexWhere((s) => s.id == sessionId);
      if (index != -1) {
        _mockChatSessions[index].rating = rating;
        
        // Notify any active room stream listeners of the update
        if (_chatRoomControllers.containsKey(sessionId)) {
          _chatRoomControllers[sessionId]!.add(_mockChatSessions[index]);
        }
        _chatSessionsController.add(List.from(_mockChatSessions));
        return null;
      }
      return "Destek oturumu bulunamadı.";
    }
  }

  /// Agent: stream of all support sessions
  static Stream<List<ChatSession>> streamChatSessions() {
    if (!useDemoMode) {
      return FirebaseFirestore.instance
          .collection('support_chats')
          .orderBy('updatedAt', descending: true)
          .snapshots()
          .map((s) => s.docs.map((d) => ChatSession.fromMap(d.data())).toList());
    }
    Future.microtask(() => _chatSessionsController.add(List.from(_mockChatSessions)));
    return _chatSessionsController.stream;
  }

  /// Customer: stream of all support sessions for a specific customer
  static Stream<List<ChatSession>> streamCustomerChatSessions(String customerId) {
    if (!useDemoMode) {
      return FirebaseFirestore.instance
          .collection('support_chats')
          .where('customerId', isEqualTo: customerId)
          .snapshots()
          .map((s) {
            final list = s.docs.map((d) => ChatSession.fromMap(d.data())).toList();
            list.sort((a, b) => b.updatedAt.compareTo(a.updatedAt));
            return list;
          });
    }
    return _chatSessionsController.stream.map(
      (sessions) {
        final filtered = sessions.where((s) => s.customerId == customerId).toList();
        filtered.sort((a, b) => b.updatedAt.compareTo(a.updatedAt));
        return filtered;
      }
    );
  }

  /// Customer: stream their own session
  static Stream<ChatSession?> streamMySession(String sessionId) {
    if (!useDemoMode) {
      return FirebaseFirestore.instance
          .collection('support_chats').doc(sessionId)
          .snapshots()
          .map((d) => d.exists ? ChatSession.fromMap(d.data()!) : null);
    }
    _chatRoomControllers.putIfAbsent(sessionId, () => StreamController<ChatSession>.broadcast());
    // Emit current state
    Future.microtask(() {
      final s = _mockChatSessions.firstWhere((x) => x.id == sessionId,
          orElse: () => ChatSession(id: '', customerId: '', customerName: '', createdAt: DateTime.now(), updatedAt: DateTime.now()));
      if (s.id.isNotEmpty) _chatRoomControllers[sessionId]?.add(s);
    });
    return _chatRoomControllers[sessionId]!.stream;
  }

  /// Agent: claim a waiting session (lock it — returns error if already claimed)
  static Future<String?> claimChatSession(String sessionId) async {
    final agent = currentUser;
    if (agent == null) return "Oturum açık değil.";

    if (!useDemoMode) {
      try {
        final ref = FirebaseFirestore.instance.collection('support_chats').doc(sessionId);
        return await FirebaseFirestore.instance.runTransaction((tx) async {
          final snap = await tx.get(ref);
          if (!snap.exists) return "Oturum bulunamadı.";
          final data = snap.data()!;
          if (data['status'] != 'waiting') return "Bu oturum zaten başka bir yetkili tarafından alındı.";
          tx.update(ref, {
            'assignedAgentId': agent.uid,
            'assignedAgentName': agent.fullName,
            'status': 'active',
            'updatedAt': DateTime.now().toIso8601String(),
          });
          return null;
        });
      } catch (e) {
        return e.toString();
      }
    } else {
      await Future.delayed(const Duration(milliseconds: 300));
      final idx = _mockChatSessions.indexWhere((s) => s.id == sessionId);
      if (idx == -1) return "Oturum bulunamadı.";
      final session = _mockChatSessions[idx];
      if (session.status != 'waiting') return "Bu oturum zaten ${session.assignedAgentName ?? 'başka bir yetkili'} tarafından alındı.";
      session.assignedAgentId = agent.uid;
      session.assignedAgentName = agent.fullName;
      session.status = 'active';
      session.updatedAt = DateTime.now();
      _chatSessionsController.add(List.from(_mockChatSessions));
      _chatRoomControllers[sessionId]?.add(session);
      return null;
    }
  }

  /// Send a chat message
  static Future<String?> sendChatMessage(String sessionId, String text, {String imageUrl = ''}) async {
    final user = currentUser;
    if (user == null) return "Oturum açık değil.";

    final msg = ChatMessage(
      id: 'msg_${DateTime.now().millisecondsSinceEpoch}',
      senderId: user.uid,
      senderName: user.fullName,
      isFromCustomer: user.role == 'customer',
      text: text,
      imageUrl: imageUrl,
      timestamp: DateTime.now(),
    );

    final displayLastMessage = imageUrl.isNotEmpty ? "[Fotoğraf]" : text;

    if (!useDemoMode) {
      try {
        final ref = FirebaseFirestore.instance.collection('support_chats').doc(sessionId);
        await ref.update({
          'messages': FieldValue.arrayUnion([msg.toMap()]),
          'lastMessage': displayLastMessage,
          'updatedAt': DateTime.now().toIso8601String(),
        });
        return null;
      } catch (e) {
        return e.toString();
      }
    } else {
      await Future.delayed(const Duration(milliseconds: 100));
      final idx = _mockChatSessions.indexWhere((s) => s.id == sessionId);
      if (idx == -1) return "Oturum bulunamadı.";
      _mockChatSessions[idx].messages = [..._mockChatSessions[idx].messages, msg];
      _mockChatSessions[idx].lastMessage = displayLastMessage;
      _mockChatSessions[idx].updatedAt = DateTime.now();
      _chatSessionsController.add(List.from(_mockChatSessions));
      _chatRoomControllers[sessionId]?.add(_mockChatSessions[idx]);
      return null;
    }
  }

  /// Close/end a chat session
  static Future<void> closeChatSession(String sessionId) async {
    if (!useDemoMode) {
      await FirebaseFirestore.instance.collection('support_chats').doc(sessionId).update({
        'status': 'closed',
        'updatedAt': DateTime.now().toIso8601String(),
      });
    } else {
      final idx = _mockChatSessions.indexWhere((s) => s.id == sessionId);
      if (idx != -1) {
        _mockChatSessions[idx].status = 'closed';
        _chatSessionsController.add(List.from(_mockChatSessions));
        _chatRoomControllers[sessionId]?.add(_mockChatSessions[idx]);
      }
    }
  }

  // ─────────────────────────────────────────
  // BRANCH INVITATIONS
  // ─────────────────────────────────────────

  /// Send a branch manager invitation to a customer by email
  static Future<String?> sendBranchInvitation(String email) async {
    final sender = currentUser;
    if (sender == null) return "Lütfen oturum açın.";

    final cleanEmail = email.trim().toLowerCase();
    if (cleanEmail.isEmpty) return "Lütfen geçerli bir e-posta adresi girin.";

    if (!useDemoMode) {
      try {
        // 1. Find user by email in Firestore
        final userSnap = await FirebaseFirestore.instance
            .collection('users')
            .where('email', isEqualTo: cleanEmail)
            .limit(1)
            .get();

        if (userSnap.docs.isEmpty) {
          return "Bu e-posta adresine sahip bir kullanıcı bulunamadı.";
        }

        final invitee = UserModel.fromMap(userSnap.docs.first.data());

        // 2. Validate role is customer
        if (invitee.role != 'customer') {
          return "Sadece normal müşterileri şube yetkilisi olarak davet edebilirsiniz.";
        }

        // 3. Check for existing pending invitation
        final inviteSnap = await FirebaseFirestore.instance
            .collection('branch_invitations')
            .where('restaurantOwnerId', isEqualTo: sender.uid)
            .where('inviteeUid', isEqualTo: invitee.uid)
            .where('status', isEqualTo: 'pending')
            .limit(1)
            .get();

        if (inviteSnap.docs.isNotEmpty) {
          return "Bu kullanıcıya zaten gönderilmiş bekleyen bir davetiniz bulunuyor.";
        }

        // 4. Create new invitation
        final inviteId = 'invite_${DateTime.now().millisecondsSinceEpoch}';
        final invitation = BranchInvitation(
          id: inviteId,
          restaurantOwnerId: sender.uid,
          restaurantName: sender.restaurantName.isNotEmpty ? sender.restaurantName : 'Şube Sahibi',
          inviteeEmail: invitee.email,
          inviteeUid: invitee.uid,
          status: 'pending',
          createdAt: DateTime.now(),
        );

        await FirebaseFirestore.instance
            .collection('branch_invitations')
            .doc(inviteId)
            .set(invitation.toMap());

        return null;
      } catch (e) {
        return e.toString();
      }
    } else {
      // Offline Demo Mode Logic
      // 1. Find mock user
      final idx = _mockUsers.indexWhere((u) => u.email.toLowerCase() == cleanEmail);
      if (idx == -1) {
        return "Bu e-posta adresine sahip bir kullanıcı bulunamadı.";
      }

      final invitee = _mockUsers[idx];

      // 2. Validate role is customer
      if (invitee.role != 'customer') {
        return "Sadece normal müşterileri şube yetkilisi olarak davet edebilirsiniz.";
      }

      // 3. Check for existing pending invitation
      final alreadyExists = _mockBranchInvitations.any((invite) =>
          invite.restaurantOwnerId == sender.uid &&
          invite.inviteeUid == invitee.uid &&
          invite.status == 'pending');

      if (alreadyExists) {
        return "Bu kullanıcıya zaten gönderilmiş bekleyen bir davetiniz bulunuyor.";
      }

      // 4. Create new invitation
      final inviteId = 'invite_${DateTime.now().millisecondsSinceEpoch}';
      final invitation = BranchInvitation(
        id: inviteId,
        restaurantOwnerId: sender.uid,
        restaurantName: sender.restaurantName.isNotEmpty ? sender.restaurantName : 'Şube Sahibi',
        inviteeEmail: invitee.email,
        inviteeUid: invitee.uid,
        status: 'pending',
        createdAt: DateTime.now(),
      );

      _mockBranchInvitations.add(invitation);
      _invitationsStreamController.add(List.from(_mockBranchInvitations));
      return null;
    }
  }

  /// Stream pending invitations for the current user
  static Stream<List<BranchInvitation>> streamBranchInvitations() async* {
    final user = currentUser;
    if (user == null) {
      yield [];
      return;
    }

    if (!useDemoMode) {
      yield* FirebaseFirestore.instance
          .collection('branch_invitations')
          .where('inviteeUid', isEqualTo: user.uid)
          .where('status', isEqualTo: 'pending')
          .snapshots()
          .map((s) => s.docs.map((d) => BranchInvitation.fromMap(d.data())).toList());
    } else {
      yield _mockBranchInvitations
          .where((invite) => invite.inviteeUid == user.uid && invite.status == 'pending')
          .toList();

      yield* _invitationsStreamController.stream.map((list) => list
          .where((invite) => invite.inviteeUid == user.uid && invite.status == 'pending')
          .toList());
    }
  }

  /// Respond to a branch invitation
  static Future<String?> respondToBranchInvitation(String inviteId, bool accept) async {
    final user = currentUser;
    if (user == null) return "Lütfen oturum açın.";

    if (!useDemoMode) {
      try {
        final docRef = FirebaseFirestore.instance.collection('branch_invitations').doc(inviteId);
        final inviteSnap = await docRef.get();
        if (!inviteSnap.exists) return "Davet bulunamadı.";

        final invitation = BranchInvitation.fromMap(inviteSnap.data()!);

        if (accept) {
          // 1. Get inviting restaurant owner's details
          final ownerSnap = await FirebaseFirestore.instance
              .collection('users')
              .doc(invitation.restaurantOwnerId)
              .get();

          String rName = 'Mahmut Usta Kebap Evi';
          String rAddress = 'Kadıköy, İstanbul';

          if (ownerSnap.exists) {
            final owner = UserModel.fromMap(ownerSnap.data()!);
            rName = owner.restaurantName.isNotEmpty ? owner.restaurantName : rName;
            rAddress = owner.restaurantAddress.isNotEmpty ? owner.restaurantAddress : rAddress;
          }

          // 2. Update user's role and copying restaurant details
          await FirebaseFirestore.instance.collection('users').doc(user.uid).update({
            'role': 'restaurant_owner',
            'restaurantName': rName,
            'restaurantAddress': rAddress,
          });

          // Update local currentUser state
          currentUser = user.copyWith(
            role: 'restaurant_owner',
            restaurantName: rName,
            restaurantAddress: rAddress,
          );
        }

        // Update invitation status
        await docRef.update({'status': accept ? 'accepted' : 'declined'});
        return null;
      } catch (e) {
        return e.toString();
      }
    } else {
      // Offline Demo Mode Logic
      final idx = _mockBranchInvitations.indexWhere((invite) => invite.id == inviteId);
      if (idx == -1) return "Davet bulunamadı.";

      final invitation = _mockBranchInvitations[idx];

      if (accept) {
        // 1. Find inviting owner
        final ownerIdx = _mockUsers.indexWhere((u) => u.uid == invitation.restaurantOwnerId);
        String rName = 'Mahmut Usta Kebap Evi';
        String rAddress = 'Kadıköy, İstanbul';

        if (ownerIdx != -1) {
          rName = _mockUsers[ownerIdx].restaurantName.isNotEmpty ? _mockUsers[ownerIdx].restaurantName : rName;
          rAddress = _mockUsers[ownerIdx].restaurantAddress.isNotEmpty ? _mockUsers[ownerIdx].restaurantAddress : rAddress;
        }

        // 2. Update invitee role in mock users
        final userIdx = _mockUsers.indexWhere((u) => u.uid == user.uid);
        if (userIdx != -1) {
          _mockUsers[userIdx] = _mockUsers[userIdx].copyWith(
            role: 'restaurant_owner',
            restaurantName: rName,
            restaurantAddress: rAddress,
          );
          currentUser = _mockUsers[userIdx];
          _usersStreamController.add(List.from(_mockUsers));
        }
      }

      _mockBranchInvitations[idx].status = accept ? 'accepted' : 'declined';
      _invitationsStreamController.add(List.from(_mockBranchInvitations));
      return null;
    }
  }
}

