// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvKvBORqmblhxEW8GlSybm5RTu10c3iME',
    appId: '1:130848354357:web:80d0a78320b4f32b76c17c',
    messagingSenderId: '130848354357',
    projectId: 'yemektarifleri-b8557',
    authDomain: 'yemektarifleri-b8557.firebaseapp.com',
    storageBucket: 'yemektarifleri-b8557.firebasestorage.app',
    measurementId: 'G-NPQHZBH7CK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgE47mUYxDcVeLBbZPQHgD3tVy_-UQC1U',
    appId: '1:130848354357:android:22136671f284256c76c17c',
    messagingSenderId: '130848354357',
    projectId: 'yemektarifleri-b8557',
    storageBucket: 'yemektarifleri-b8557.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDG96XzHIkmzFZmItFxJYGKVqSUwgXVxgo',
    appId: '1:130848354357:ios:8f8538ad28c8c02876c17c',
    messagingSenderId: '130848354357',
    projectId: 'yemektarifleri-b8557',
    storageBucket: 'yemektarifleri-b8557.firebasestorage.app',
    iosBundleId: 'com.example.yemektarifiapp',
  );
}
